[package]
name = "mathop"
version = "0.1.5"
authors = ["Sidra Shakeel <sidrashakeel19@hotmail.com"]
edition = "2018"
description = "Library for math operations"
license = "MIT"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
